DROP TABLE IF EXISTS worker CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS coordinates CASCADE;